import type { BootcampDayContent } from "@/lib/models";
import { CHAPTERS_1_2_TEXT, CHAPTER_3_TEXT, CHAPTERS_4_5_TEXT } from "@/lib/seed-data/source-text";

// Curriculum ported from the "AI Bootcamp - 3 Day Training Program" document,
// which was itself built from ARTIFICIAL INTELLIGENCE BOOTCAMP.docx (Chapters 1-5).

export const bootcampSeedContent: Omit<BootcampDayContent, "_id">[] = [
  {
    dayNumber: 1,
    title: "Foundations of Artificial Intelligence",
    chaptersCovered: "Chapter 1: Introduction to AI & Chapter 2: Types of AI and Core Technologies",
    learningObjectives: [
      "Define artificial intelligence in plain language and give three real-world examples encountered daily.",
      "Explain the fundamental differences between human cognition and machine intelligence.",
      "Recall the four key milestones in AI history (Dartmouth 1956, AI Winters, Deep Blue 1997, the Deep Learning explosion post-2010).",
      "Differentiate between Artificial Narrow AI (ANI), Artificial General AI (AGI), and Artificial Super AI (ASI).",
      "Explain how Machine Learning differs from traditional rule-based programming.",
      "Describe how a neural network is structured and how backpropagation improves accuracy.",
      "Identify the three core branches of AI technology (NLP, Computer Vision, Predictive ML).",
    ],
    lessons: [
      { id: "d1-l1", title: "What Is AI, and Why Does It Matter?", summary: "Strips away Hollywood myths of AI; defines AI as software performing human-like cognitive tasks, with everyday examples (Face ID, translation, chess)." },
      { id: "d1-l2", title: "Human Brain vs. Artificial Intelligence", summary: "Compares learning source, processing style, understanding, and energy consumption between humans and AI, using the 'chair' analogy." },
      { id: "d1-l3", title: "A Brief History of AI", summary: "Dartmouth 1956, the AI Winters, Deep Blue vs. Kasparov (1997), and the post-2010 Deep Learning explosion (Big Data, GPUs, Cloud)." },
      { id: "d1-l4", title: "The Three Levels of AI: ANI, AGI, ASI", summary: "Artificial Narrow AI (all AI today), theoretical Artificial General AI, and theoretical Artificial Super AI." },
      { id: "d1-l5", title: "Machine Learning: The Engine of Modern AI", summary: "Contrasts hand-coded rule-based programming with ML, where the model learns its own statistical rules from labeled data." },
      { id: "d1-l6", title: "Deep Learning & Neural Networks", summary: "Input Layer, Hidden Layers, Output Layer, and backpropagation as the error-correction mechanism." },
      { id: "d1-l7", title: "Core Branches: NLP, Computer Vision & Predictive ML", summary: "The three dominant AI branches and where each shows up in the real world." },
    ],
    liveDemonstrations: [
      "Unlock a phone with Face ID and run a live translation app to show AI in everyday life.",
      "Live-prompt a chatbot: 'Explain derivatives to me as if I am a 10-year-old who loves skateboarding.'",
      "Use a browser-based image classifier to show how many example photos train a model to recognize an object (ties to the chair analogy).",
      "Play a few live moves against a chess engine to illustrate ANI strength vs. the flexibility AGI would require.",
    ],
    practicalActivities: [
      "'Spot the AI' Scavenger Hunt - list 10 AI systems used in the last 24 hours and categorize each by branch.",
      "Build-a-Neuron Worksheet - trace how input pixels flow through hidden layers to classify 'cat vs. dog'.",
      "AI History Timeline Build - arrange history cards (Dartmouth, AI Winters, Deep Blue, 2010+) in order.",
    ],
    individualExercise:
      "Write a 150-200 word reflection: describe one task you do that could be automated by ANI today, and explain why it could NOT be handled by the same system if the task changed slightly.",
    groupExercise:
      "Debate in groups of four: 'Will AGI ever be achieved, and should it be pursued?' Two groups argue for, two against.",
    quickQuiz: [
      { id: "d1-q1", question: "In one sentence, define Artificial Intelligence in your own words." },
      { id: "d1-q2", question: "Name the three layers of an artificial neural network." },
      { id: "d1-q3", question: "In what year, and at what event, was the field of AI formally founded?" },
      { id: "d1-q4", question: "What is the core difference between ANI and AGI?" },
      { id: "d1-q5", question: "Name the three core branches of AI technology introduced in Chapter 2." },
    ],
    mcqs: [
      { id: "d1-mcq1", question: 'What does modern AI primarily rely on to "understand" the world?', options: ["Emotional empathy", "Statistical pattern recognition from data", "Physical senses", "Lived experience"], correctIndex: 1 },
      { id: "d1-mcq2", question: 'Why can a toddler learn "chair" from 2-3 examples but an AI needs thousands?', options: ["AI has no memory", "Humans have more emotional context", "AI lacks embodied experience and must isolate patterns purely from pixel data", "Toddlers use more energy"], correctIndex: 2 },
      { id: "d1-mcq3", question: "The field of Artificial Intelligence was formally founded at:", options: ["MIT in 1969", "Dartmouth College in 1956", "Stanford in 1975", "IBM in 1997"], correctIndex: 1 },
      { id: "d1-mcq4", question: 'What caused the "AI Winters" of the 1970s-1980s?', options: ["Lack of researcher interest", "Insufficient processing power/memory leading to failed promises and funding cuts", "Government bans on AI", "The invention of GPUs"], correctIndex: 1 },
      { id: "d1-mcq5", question: "Deep Blue's 1997 victory over Garry Kasparov demonstrated that:", options: ["AGI had been achieved", "Computers could excel at narrow, structured tasks using raw computational speed", "Chess is not a good test of intelligence", "Machine learning had replaced rule-based programs"], correctIndex: 1 },
      { id: "d1-mcq6", question: "Which THREE forces converged after 2010 to fuel the Deep Learning explosion?", options: ["Big Data, GPUs, Cloud Infrastructure", "Robotics, Blockchain, 5G", "AI Winters, Deep Blue, Dartmouth", "NLP, Computer Vision, Predictive ML"], correctIndex: 0 },
      { id: "d1-mcq7", question: "An ANI system that recommends songs on a music app:", options: ["Can also diagnose X-rays if retrained instantly", "Cannot perform tasks outside its trained domain", "Is an example of AGI", "Understands music emotionally"], correctIndex: 1 },
      { id: "d1-mcq8", question: "In traditional (non-ML) programming, a spam filter fails when spammers misspell words because:", options: ["The model has too many parameters", "Explicit hand-coded rules no longer match the new pattern", "The neural network has too few layers", "Tokenization breaks down"], correctIndex: 1 },
      { id: "d1-mcq9", question: "In a deep neural network trained for image recognition, early hidden layers typically detect:", options: ['Full objects like "golden retriever"', "Basic lines and edges", "Complete sentences", "Token IDs"], correctIndex: 1 },
      { id: "d1-mcq10", question: "Which branch of AI powers voice assistants like Siri and Alexa?", options: ["Computer Vision", "Natural Language Processing", "Core Predictive Machine Learning", "Artificial Super AI"], correctIndex: 1 },
    ],
    scenarios: [
      { id: "d1-s1", question: "A hospital wants an AI system that can read X-rays AND independently decide on a full treatment plan AND explain its reasoning empathetically to a scared patient. Which level of AI would this require, and does it exist today?", modelAnswer: "This describes AGI-level flexibility (cross-domain reasoning + emotional communication + independent judgment), which does not exist today. Current hospital AI (X-ray analysis) is ANI - narrow, single-task." },
      { id: "d1-s2", question: "Using the chair analogy, why might a self-driving car's vision system fail to recognize a snow-covered stop sign that a human still recognizes instantly?", modelAnswer: "The AI only recognizes patterns it has seen enough labeled examples of; if snow-covered stop signs were underrepresented in training data, the pixel pattern won't match learned weights closely enough. A human generalizes conceptually even with partial obstruction." },
      { id: "d1-s3", question: 'A friend claims a modern chatbot is "basically an AGI" because it can write essays, code, and answer trivia. Why is this inaccurate?', modelAnswer: "The chatbot is a very broad, capable ANI trained on huge diverse text data. It doesn't truly understand, can't act in the physical world, doesn't self-improve, and lacks the general cross-domain autonomous reasoning that defines AGI." },
      { id: "d1-s4", question: "A school wants to predict which students are at risk of failing this semester using past grades, attendance, and scores. Which core branch of AI is most relevant?", modelAnswer: "Core Predictive Machine Learning - the data is structured, and the goal is forecasting/trend detection." },
    ],
    handsOnAssignment:
      'The "AI Audit": identify 5 AI-powered features in an app/website you use, explain which branch of AI each uses, and confirm each is ANI with a one-sentence justification.',
    trainerNotes: [
      "Common misconception: students often believe AGI already exists because chatbots are fluent - correct this explicitly.",
      "Pre-load the phone/translation demo before class in case of Wi-Fi issues; keep a screenshot backup.",
      "The history timeline activity works well as a physical card sort if printed.",
      "During the AGI debate, actively rotate facilitation between groups to keep quieter students engaged.",
    ],
    sourceExcerpt: CHAPTERS_1_2_TEXT,
  },
  {
    dayNumber: 2,
    title: "Generative AI & Large Language Models",
    chaptersCovered: "Chapter 3: Generative AI & Large Language Models",
    learningObjectives: [
      "Explain how Generative AI differs from discriminative/traditional AI models.",
      "Describe how LLMs use tokenization to process language.",
      "Explain the role of parameters, weights, and biases in an LLM's knowledge.",
      "Explain the Transformer architecture and self-attention (Query, Key, Value).",
      'Explain how RAG solves the "frozen in time" problem of LLMs.',
      "Compare Prompt Engineering, RAG, and Fine-Tuning, including cost/complexity trade-offs.",
      "Explain how hybrid architectures combine all three techniques in production systems.",
    ],
    lessons: [
      { id: "d2-l1", title: "The Generative AI Revolution", summary: "Discriminative vs. generative models, and the three core shifts of the Generative AI revolution." },
      { id: "d2-l2", title: "Large Language Models: How They Work", summary: "An LLM as a massively scaled-up version of smartphone predictive text, trained on trillions of pages of text." },
      { id: "d2-l3", title: "Tokenization: The Fuel of Language Models", summary: 'How prompts are broken into tokens and converted into numerical IDs, e.g. "unforgettable" -> "un"+"forget"+"table".' },
      { id: "d2-l4", title: "Parameters, Weights, and Biases", summary: "An LLM's knowledge lives in its parameters, not a fact database; 'Large' refers to parameter scale." },
      { id: "d2-l5", title: "The Transformer Architecture & Self-Attention", summary: '"Attention Is All You Need" (2017), the sequential-forgetting limitation of RNNs/LSTMs, and Query/Key/Value vectors.' },
      { id: "d2-l6", title: "Retrieval-Augmented Generation (RAG)", summary: "How RAG retrieves live, verified facts and bundles them with the prompt before generation, like an open-book exam." },
      { id: "d2-l7", title: "Fine-Tuning vs. RAG vs. Prompt Engineering + Hybrid Architectures", summary: "Comparing the three tailoring strategies by mechanism, best use case, and cost/complexity, and how production systems combine all three." },
    ],
    liveDemonstrations: [
      'Use a public tokenizer tool to type "unforgettable" and show token splits/IDs live.',
      "Ask an LLM about a very recent event with no context, then again after pasting a relevant article as context, to illustrate RAG.",
      'Project the ambiguous sentence "The bank of the river was muddy, so the traveler did not step on it" and ask the AI to explain what "it" refers to.',
      "Run the same base prompt plainly, then again with a well-engineered version, to show the difference in output quality.",
    ],
    practicalActivities: [
      "Tokenize It! - manually split 5 words/sentences into likely tokens before checking a tokenizer tool.",
      "Attention Mapping - draw arrows connecting pronouns/ambiguous words to their correct referents in 3 sentences.",
      "RAG Pipeline Storyboard - storyboard a RAG pipeline for a campus helpdesk bot.",
    ],
    individualExercise:
      "Choose one real business problem and decide whether Prompt Engineering, RAG, or Fine-Tuning is the best solution; write a 150-word justification.",
    groupExercise:
      'In teams of 3-4, design a "Hybrid AI Architecture" pitch (medical chatbot, legal research assistant, or customer support bot) and present a 3-minute pitch.',
    quickQuiz: [
      { id: "d2-q1", question: "What is the key difference between a discriminative model and a generative model?" },
      { id: "d2-q2", question: 'What is a "token," and give an example of how a word might be split into tokens.' },
      { id: "d2-q3", question: "Where does an LLM's knowledge actually live?" },
      { id: "d2-q4", question: "What problem does Retrieval-Augmented Generation (RAG) solve?" },
      { id: "d2-q5", question: "Name the three methods for tailoring an LLM discussed in Chapter 3." },
    ],
    mcqs: [
      { id: "d2-mcq1", question: "Generative AI differs from traditional discriminative AI because it:", options: ["Only sorts data into categories", "Creates original new content from learned patterns", "Requires no training data", "Only works with numbers"], correctIndex: 1 },
      { id: "d2-mcq2", question: 'When an LLM processes the prompt "Generative AI is shifting paradigms," what does it do first?', options: ["Executes code", "Breaks the text into tokens and converts them to numerical IDs", "Searches the internet", "Applies backpropagation"], correctIndex: 1 },
      { id: "d2-mcq3", question: 'The "Large" in Large Language Model refers to:', options: ["The size of the training servers", "The scale of parameters (billions to trillions)", "The number of users", "The number of hidden layers only"], correctIndex: 1 },
      { id: "d2-mcq4", question: "The Transformer architecture was introduced in which landmark paper?", options: ['"Attention Is All You Need" (2017)', '"A Brief History of Time"', '"Deep Blue Wins"', '"The Dartmouth Proposal"'], correctIndex: 0 },
      { id: "d2-mcq5", question: "What limitation did RNNs/LSTMs have that Transformers solved?", options: ["They used too many GPUs", 'They processed text sequentially and tended to "forget" earlier context in long text', "They could not use tokens", "They were too fast"], correctIndex: 1 },
      { id: "d2-mcq6", question: "In the self-attention mechanism, what does the Query represent?", options: ["What a word is searching for/asking about", "The final answer", "The training dataset", "The token ID"], correctIndex: 0 },
      { id: "d2-mcq7", question: 'Why do LLMs sometimes "hallucinate" or fail on very recent events?', options: ["They are intentionally dishonest", "Their knowledge is frozen at the end of training", "Tokenization removes recent words", "They lack parameters"], correctIndex: 1 },
      { id: "d2-mcq8", question: "Which technique is BEST for teaching a model a highly specialized medical or legal tone baked into the model itself?", options: ["Prompt Engineering", "RAG", "Fine-Tuning", "Tokenization"], correctIndex: 2 },
      { id: "d2-mcq9", question: "Which technique has the LOWEST cost/complexity?", options: ["Fine-Tuning", "Prompt Engineering", "RAG", "Building a new Transformer"], correctIndex: 1 },
      { id: "d2-mcq10", question: "A production agent combining fine-tuned tone, RAG-supplied live data, and engineered prompts is an example of:", options: ["An AI Winter", "Artificial Narrow AI failure", "A hybrid architecture", "Algorithmic bias"], correctIndex: 2 },
    ],
    scenarios: [
      { id: "d2-s1", question: "A law firm wants its AI assistant to always cite the most recent case law (updated weekly) without retraining the model every week. Which technique should they use?", modelAnswer: "RAG - it retrieves live, verified documents from a database at query time, avoiding constant expensive retraining." },
      { id: "d2-s2", question: "An LLM confidently gives a detailed but false answer about yesterday's stock market event. What is this called, and how should the user verify it?", modelAnswer: "This is a hallucination. The user should check the primary source, look for logical leaps, and use RAG/web tools to verify rather than trusting the LLM outright." },
      { id: "d2-s3", question: 'In "The trophy didn\'t fit in the suitcase because it was too big," how does self-attention resolve what "it" refers to?', modelAnswer: 'Self-attention lets the model weigh the relationship between "it" and both "trophy" and "suitcase" simultaneously, using contextual/size logic to correctly link "it" to "trophy".' },
      { id: "d2-s4", question: "A startup has a small budget and needs a well-formatted chatbot by next week, with no ability to retrain models. Which strategy should they lean on most?", modelAnswer: "Prompt Engineering - extremely low cost/complexity, fast to iterate, well suited for quick formatting and reasoning improvements." },
    ],
    handsOnAssignment:
      'The "Prompt Engineering Lab": take one unhelpful/vague prompt and iteratively refine it three times; submit all four versions plus outputs and a reflection on what changed.',
    trainerNotes: [
      "This is the most technically dense day - pace carefully and lean on the predictive-text analogy before the attention formula.",
      "Do not dwell on the mathematics of softmax - keep it conceptual to avoid math anxiety.",
      "Confirm the tokenizer/chat tools are not blocked by any firewall before class; keep screenshot backups.",
      "Reinforce that RAG and Fine-Tuning are not mutually exclusive - most production systems use a hybrid.",
    ],
    sourceExcerpt: CHAPTER_3_TEXT,
  },
  {
    dayNumber: 3,
    title: "AI Applications, Ethics, and the Future Landscape",
    chaptersCovered: "Chapter 4: AI Applications & Ethics & Chapter 5: The AI Landscape & Future Trends",
    learningObjectives: [
      "Identify how AI is applied across healthcare, banking/finance, creative industries, and sports analytics.",
      "Explain algorithmic bias, including causes and mitigation strategies.",
      "Define AI hallucinations and apply the Fact-Checking Checklist to verify AI output.",
      "Explain the risks of deepfakes and identify preventive measures.",
      "Discuss privacy/surveillance, environmental impact, accountability, and workforce ethics.",
      "Compare proprietary vs. open-source AI models.",
      "Identify emerging AI career paths that do not require advanced math or coding.",
      "Describe five key future trends in AI.",
    ],
    lessons: [
      { id: "d3-l1", title: "AI in Healthcare & Banking/Finance", summary: "Diagnostics, drug discovery, ICU prediction, wearables; fraud detection, algorithmic trading, risk simulation, banking chatbots." },
      { id: "d3-l2", title: "AI in Creative Industries & Sports Analytics", summary: "Generative design, hyper-personalized marketing; player tracking, injury prevention, fan engagement, automated highlights." },
      { id: "d3-l3", title: "Algorithmic Bias", summary: "AI has no innate concept of fairness and replicates training-data prejudice; mitigation strategies." },
      { id: "d3-l4", title: "Hallucinations & the Fact-Checking Checklist", summary: "Confident but fabricated AI output, and the three-step verification checklist." },
      { id: "d3-l5", title: "Deepfakes & Information Integrity", summary: "Synthetic audio/video impersonation risks and preventive measures." },
      { id: "d3-l6", title: "Privacy, Environment, Accountability & Workforce Ethics", summary: "Surveillance, environmental cost, unresolved accountability questions, and workforce reskilling." },
      { id: "d3-l7", title: "Proprietary vs. Open-Source AI", summary: "Closed-source corporate models vs. open-source models, and their respective pros/cons." },
      { id: "d3-l8", title: "Future AI Careers & Future Trends", summary: "Non-technical AI careers and five future trends: Edge AI, Multimodal AI, AI Regulation, Green AI, Collaborative AI." },
    ],
    liveDemonstrations: [
      "Walk through a simulated bank-app fraud alert to illustrate real-time transaction monitoring.",
      "Deliberately prompt an LLM for an obscure fact likely to be hallucinated, then live fact-check it with the checklist.",
      "Review a published, clearly labeled deepfake-awareness research example to discuss detection cues.",
      "Compare a proprietary AI tool's chat interface with an open-source model running locally.",
    ],
    practicalActivities: [
      "Industry Mapping Carousel - poster stations for Healthcare, Banking, Creative, and Sports.",
      "Bias Detective - review a fictional AI hiring-tool case study and identify where bias entered.",
      "Fact-Check Sprint - apply the checklist to 3 AI-generated statements (one true, two subtly wrong).",
    ],
    individualExercise:
      "Write a 150-200 word position statement on who should be accountable when an AI system causes harm.",
    groupExercise:
      "Roleplay debate - 'Proprietary vs. Open-Source': each group argues which model type their assigned stakeholder would prefer.",
    quickQuiz: [
      { id: "d3-q1", question: "Name the four industries highlighted in Chapter 4." },
      { id: "d3-q2", question: "What is algorithmic bias, and where does it come from?" },
      { id: "d3-q3", question: "What are the three steps in the Fact-Checking Checklist?" },
      { id: "d3-q4", question: "Name one pro and one con of open-source AI models." },
      { id: "d3-q5", question: "Name three of the five future AI trends discussed in Chapter 5." },
    ],
    mcqs: [
      { id: "d3-mcq1", question: "AI-powered predictive analytics in ICUs is used to:", options: ["Replace doctors entirely", "Forecast patient deterioration before a crisis", "Generate synthetic patient records", "Only track billing"], correctIndex: 1 },
      { id: "d3-mcq2", question: "When your credit card purchase is flagged as suspicious in real time, which AI application is at work?", options: ["Sports analytics", "Fraud detection in banking/finance", "Computer vision in healthcare", "Creative marketing"], correctIndex: 1 },
      { id: "d3-mcq3", question: "An AI hiring tool that downgrades female applicants due to biased historical data is an example of:", options: ["A hallucination", "Algorithmic bias", "A deepfake", "Green AI"], correctIndex: 1 },
      { id: "d3-mcq4", question: "Which is NOT one of the three Fact-Checking Checklist steps?", options: ["Check the primary reference source", "Look for logical leaps in the model's steps", "Ask the same LLM to grade its own answer", "Use RAG/web tools to double-verify dates"], correctIndex: 2 },
      { id: "d3-mcq5", question: "Deepfakes primarily threaten society by:", options: ["Reducing computing costs", "Enabling misinformation, scams, and reputational damage via synthetic audio/video", "Improving fact-checking speed", "Increasing model transparency"], correctIndex: 1 },
      { id: "d3-mcq6", question: 'Which is a listed "additional ethical consideration" beyond bias, hallucination, and deepfakes?', options: ["Tokenization limits", "Environmental impact of training large models", "Self-attention formulas", "GPU shortages only"], correctIndex: 1 },
      { id: "d3-mcq7", question: "A key advantage of proprietary AI models is:", options: ["Free unlimited local use", "Continuous updates backed by warehouse-scale infrastructure", "Full transparency of training data", "No subscription fees"], correctIndex: 1 },
      { id: "d3-mcq8", question: "A key advantage of open-source models is:", options: ["Zero setup responsibility", "Total data privacy since they can run offline", "Automatic fine-tuning APIs", "Guaranteed superior accuracy"], correctIndex: 1 },
      { id: "d3-mcq9", question: "Which career focuses on organizing and securing knowledge bases that power RAG systems?", options: ["AI Product Manager", "Vector Database Coordinator", "Data Annotation Manager", "AI UX Designer"], correctIndex: 1 },
      { id: "d3-mcq10", question: '"Edge AI" refers to:', options: ["Running AI models on cloud supercomputers only", "Running AI directly on local devices for real-time decisions without cloud dependency", "Training models exclusively on financial data", "A theoretical form of ASI"], correctIndex: 1 },
    ],
    scenarios: [
      { id: "d3-s1", question: "A streaming platform's AI recommendation engine maximizes engagement with no fairness review. What ethical risk does this raise?", modelAnswer: "Could raise algorithmic bias and workforce/social responsibility concerns; mitigation includes bias audits and transparent reporting of recommendation logic." },
      { id: "d3-s2", question: "An AI assistant gives a confident but fabricated legal citation. How would you apply the Fact-Checking Checklist before submitting it?", modelAnswer: "Check the primary source, look for logical leaps, and use a RAG/web-connected legal tool to verify the citation exists." },
      { id: "d3-s3", question: "A hospital IT director needs full data privacy and cannot use third-party servers, but has a strong in-house engineering team. Proprietary or open-source?", modelAnswer: "Open-source - it can run fully offline for total data privacy, and the hospital has the technical capacity to manage it in-house." },
      { id: "d3-s4", question: "A student wants an AI-adjacent career with no interest in advanced math or coding. Recommend one role.", modelAnswer: "E.g., AI Product Manager (strategic thinking, communication) or Data Annotation Manager (project management, attention to detail, QA)." },
    ],
    handsOnAssignment:
      'The "Ethics & Career Capstone": choose one industry, describe an AI application, an ethical risk, a mitigation strategy, and a relevant AI-adjacent career path.',
    trainerNotes: [
      "Encourage respectful debate norms for the accountability/bias discussions.",
      "Keep the deepfake demo strictly to labeled/consented educational examples.",
      "Tie the future-careers lesson to students' own majors/interests.",
      "Reserve time at the end of Day 3 for the Final Assessment.",
    ],
    sourceExcerpt: CHAPTERS_4_5_TEXT,
  },
];
